# Generated by Django 2.1.7 on 2019-03-23 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del evento')),
                ('descripcion', models.CharField(max_length=70, verbose_name='Descripción del evento')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('lugar', models.CharField(max_length=100, verbose_name='Lugar del evento')),
                ('url', models.URLField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Cancelado', 'Cancelado'), ('Finalizado', 'Finalizado')], default='Activo', max_length=20)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de localidad')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='LocalidadesEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidad', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('disponibilidad', models.IntegerField()),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evento_localidades_del_evento', to='eventos.Evento')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evento_localidades_de_localidades', to='eventos.Localidad')),
            ],
            options={
                'ordering': ['localidades__nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Tipo de evento')),
            ],
        ),
        migrations.AddField(
            model_name='localidad',
            name='tipo_de_evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localidades_del_tipo', to='eventos.TipoEvento', verbose_name='Tipo de evento'),
        ),
        migrations.AddField(
            model_name='evento',
            name='tipo_de_evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_del_tipo', to='eventos.TipoEvento'),
        ),
    ]
