# Generated by Django 2.1.7 on 2019-02-16 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Event's name")),
                ('description', models.CharField(max_length=70, verbose_name="Event's description")),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('event_place', models.CharField(max_length=100, verbose_name='Location')),
                ('event_url', models.URLField(blank=True, max_length=100)),
                ('event_status', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Cancelado', 'Cancelado'), ('Finalizado', 'Finalizado')], default='Activo', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EventLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Event type')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Location's name")),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.EventType')),
            ],
        ),
        migrations.AddField(
            model_name='eventlocation',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.EventType'),
        ),
        migrations.AddField(
            model_name='eventlocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.EventType'),
        ),
    ]
