# Generated by Django 2.1.7 on 2019-03-24 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localidadesevento',
            options={'ordering': ['localidad__nombre']},
        ),
    ]
