# Generated by Django 2.1.7 on 2019-03-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_auto_20190324_0134'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProveedorEventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('api_url', models.CharField(max_length=300)),
            ],
        ),
    ]
