# Generated by Django 2.1.7 on 2019-02-16 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_auto_20190215_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventlocation',
            name='event_type',
        ),
        migrations.AddField(
            model_name='eventlocation',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eventos.Event'),
            preserve_default=False,
        ),
    ]
