# Generated by Django 2.1.7 on 2019-02-27 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_auto_20190224_2335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventlocation',
            options={'ordering': ['location__name']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='eventlocation',
            name='availability',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
