# Generated by Django 2.1.7 on 2019-03-25 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='perfiladministrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=64)),
                ('cedula', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='es_administrador',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfiladministrador',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
