# Generated by Django 2.1.7 on 2019-03-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfilcliente_perfilgerente_perfilvendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilcliente',
            name='cedula',
            field=models.IntegerField(default=1122334455, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfilgerente',
            name='cedula',
            field=models.IntegerField(default=1122334455, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfilvendedor',
            name='cedula',
            field=models.IntegerField(default=1122334455, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
