# Generated by Django 2.1.7 on 2019-03-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20190322_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilcliente',
            name='cedula',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='perfilgerente',
            name='cedula',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='perfilvendedor',
            name='cedula',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
