# Generated by Django 2.1.7 on 2019-02-27 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0006_auto_20190227_0600'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletos_de_event_location', to='eventos.EventLocation', verbose_name='EventLocation')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletos_de_la_venta', to='ventas.Sale', verbose_name='Sale')),
            ],
        ),
    ]
