# Generated by Django 2.1.7 on 2019-03-23 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidades_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletos_de_event_location', to='eventos.LocalidadesEvento', verbose_name='LocalidadesEvento')),
            ],
        ),
    ]
