# Generated by Django 2.1.7 on 2019-03-23 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendedor', models.CharField(max_length=100, verbose_name='Seller')),
                ('fecha', models.DateTimeField(editable=False)),
                ('subtotal', models.IntegerField(default=0)),
                ('iva', models.FloatField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('terminada', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_del_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
