# Generated by Django 2.1.7 on 2019-03-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_auto_20190318_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='iva',
            field=models.FloatField(default=0),
        ),
    ]
